Repository k-jipgeria/FE11-part4-team1-coworkers, pull requests merged in 2025-01, with the labels that each got.

#10 Chore/8 add common image
  app/page.tsx
  public/icons/alert.svg
  public/icons/arrow-left.svg
  public/icons/arrow-right.svg
  public/icons/check.svg
  public/icons/checkbox-active.svg
  public/icons/checkbox-default.svg
  public/icons/comment.svg
  public/icons/done.svg
  public/icons/gear.svg
  public/icons/gnb-menu.svg
  public/icons/icon_calendar.svg
  public/icons/icon_repeat.svg
  public/icons/icon_time.svg
  public/icons/img.svg
  public/icons/kebab-big-button.svg
  public/icons/kebab-small-button.svg
  public/icons/list.svg
  public/icons/plus.svg
  public/icons/progress-done.svg
  public/icons/progress-ongoing.svg
  public/icons/search.svg
  public/icons/toggle.svg
  public/icons/user.svg
  public/icons/visibility_off.svg
  public/icons/visibility_on.svg
  public/icons/x.svg
  public/images/google.png
  public/images/img_done.png
  public/images/img_todo.png
  public/images/kakaotalk.png
  public/images/landing-bottom-large.png
  public/images/landing-bottom-medium.png
  public/images/landing-bottom-small.png
  public/images/landing-top-large.png
  public/images/landing-top-medium.png
  public/images/landing-top-small.png
  public/images/logo-large.png
  public/images/logo-small.png
  public/images/thumbnail_team.png
Labels: chore

#14 fix: 절대 경로 설정
  tsconfig.json
Labels: fix

#16 Feat/9 define device type using width
  app/_hooks/.gitkeep
  app/_hooks/useResize.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feature

#18 feat: 공통 모달 컴포넌트 구현 및 zustand, react-query 설치
  app/_components/common/Modal.tsx
  app/_store/modal-store.ts
  app/modal-test/page.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feature

#19 Feat/17 adjust root font size
  app/globals.css
Labels: feature

#21 feat: axios 인스턴스, 토큰 갱신 기능 추가, react query 초기 세팅
  app/_lib/QueryProvider.tsx
  app/api/axios-instance.ts
  app/layout.tsx
  package-lock.json
  package.json
Labels: feature

#25 Feat/11 공통 버튼 컴포넌트
  app/_components/Button.tsx
  app/button-test/page.tsx
  package-lock.json
  public/icons/check-white.svg
Labels: feature

#28 feat: 회원가입 및 로그인 api 구현
  app/_hooks/useAuth.ts
  app/_store/auth-store.ts
  app/api/auth.ts
  app/api/axios-instance.ts
  package-lock.json
Labels: feature

#29 feat: 공통 헤더 구현 완료
  app/_components/.gitkeep
  app/_components/common/Header/GnbButton.tsx
  app/_components/common/Header/TeamSelector.tsx
  app/_components/common/Header/UserAccount.tsx
  app/_components/common/Header/index.tsx
  app/_store/.gitkeep
  app/_types/.gitkeep
  app/api/.gitkeep
  app/layout.tsx
  app/page.tsx
  next.config.ts
  public/icons/.gitkeep
  public/icons/default-team-icon.svg
  public/icons/logo.svg
  public/images/.gitkeep
  public/images/logo-large.png
  public/images/logo-small.png
Labels: feature

#30 refactor: 모달 테스트 페이지 수정 (단위, 버튼 컴포넌트 사용)
  app/modal-test/page.tsx
Labels: refactor

#35 feat/팀페이지 멤버 섹션
  app/[teamid]/page.tsx
  app/_components/TeamPage/MemberCard.tsx
  app/_components/TeamPage/MemberSection.tsx
  app/_components/common/Button.tsx
  app/button-test/page.tsx
  app/modal-test/page.tsx
  public/icons/member.svg
Labels: feature

#37 (routes) 폴더 안으로 페이지 폴더 이동
  app/(routes)/.gitkeep
  app/(routes)/[teamid]/page.tsx
  app/(routes)/button-test/page.tsx
  app/(routes)/dropdown-test/page.tsx
  app/(routes)/modal-test/page.tsx
  app/_components/layout/Header/GnbButton.tsx
  app/_components/layout/Header/TeamSelector.tsx
  app/_components/layout/Header/UserAccount.tsx
  app/_components/layout/Header/index.tsx
  app/layout.tsx
Labels: chore

#42 build: dayjs 라이브러리 설치, date & time 포메팅을 위한
  package-lock.json
  package.json
Labels: chore

#44 feat: 공통 배경 색 body에 추가
  app/globals.css
Labels: feature

#40 Feat/36 팀페이지 할일 목록 섹션
  app/(routes)/team/[teamid]/page.tsx
  app/_components/TeamPage/TodoListCard.tsx
  app/_components/TeamPage/TodoListCheckBox.tsx
  app/_components/TeamPage/TodoListSection.tsx
Labels: feature

#49 feat: add task card component UI
  app/(routes)/tasklist/_components/TaskCard.tsx
  app/(routes)/tasklist/page.tsx
Labels: feature

#51 Feat/50 not found page
  app/globals.css
  app/not-found.tsx
Labels: feature

#56 Feat: 팀페이지 리포트 컴포넌트
  app/(routes)/team/[teamid]/page.tsx
  app/_components/TeamPage/MemberSection.tsx
  app/_components/TeamPage/ReportCard.tsx
  app/_components/TeamPage/ReportSection.tsx
Labels: feature

#62 리스트 페이지 날짜 선택 컴포넌트 구현
  app/(routes)/tasklist/_components/DateSelector.tsx
  app/(routes)/tasklist/page.tsx
  app/_components/common/ShadCN/Calendar/button.tsx
  app/_components/common/ShadCN/Calendar/calendar.tsx
  app/_components/common/ShadCN/Popover/popover.tsx
  app/_lib/utils/format-date.ts
  app/lib/utils.ts
  components.json
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feature

#67 리스트 목록 선택 컴포넌트
  app/(routes)/task-list/_components/DateSelector.tsx
  app/(routes)/task-list/_components/TaskCard.tsx
  app/(routes)/task-list/_components/TaskListNav.tsx
  app/(routes)/task-list/page.tsx
Labels: feature

#70 feat: 모달 UI 및 일부 기능 구현
  app/(routes)/modal-test/page.tsx
  app/_components/common/Button.tsx
  app/_components/common/Modal.tsx
  app/_components/modal/AddTaskListModal.tsx
  app/_components/modal/AddTaskModal.tsx
  app/_components/modal/CalendarInModal.tsx
  app/_components/modal/ChangePasswordModal.tsx
  app/_components/modal/DeleteTaskModal.tsx
  app/_components/modal/DeleteUserModal.tsx
  app/_components/modal/MemberInviteModal.tsx
  app/_components/modal/ProfileModal.tsx
  app/_components/modal/ResetPasswordModal.tsx
  package-lock.json
  package.json
  public/icons/ic_arrow-left.svg
  public/icons/ic_arrow-right.svg
  tailwind.config.ts
Labels: feature

#71 feat: api 및 react query 훅 작성
  app/_hooks/useArticle.ts
  app/_hooks/useArticleComment.ts
  app/_hooks/useComment.ts
  app/_hooks/useImage.ts
  app/_hooks/useLike.ts
  app/_hooks/useTask.ts
  app/_hooks/useTaskList.ts
  app/_lib/api/article-api.ts
  app/_lib/api/article-comment-api.ts
  app/_lib/api/comment-api.ts
  app/_lib/api/image-api.ts
  app/_lib/api/like-api.ts
  app/_lib/api/task-api.ts
  app/_lib/api/tasklist-api.ts
Labels: feature

#72 Feat: 팀페이지 작업
  app/(routes)/dropdown-test/page.tsx
  app/(routes)/team/[teamid]/page.tsx
  app/_components/TeamPage/MemberCard.tsx
  app/_components/TeamPage/MemberSection.tsx
  app/_components/TeamPage/ReportCard.tsx
  app/_components/TeamPage/ReportSection.tsx
  app/_components/TeamPage/TeamHeader.tsx
  app/_components/TeamPage/TodoListCard.tsx
  app/_components/TeamPage/TodoListSection.tsx
Labels: feature
