Repository k-jipgeria/FE11-part4-team1-coworkers, pull requests merged in 2025-02, with the labels that each got.

#73 feat: 기본 input, email input, password input 컴포넌트
  app/_components/common/Input/EmailInput.tsx
  app/_components/common/Input/Input.tsx
  app/_components/common/Input/PasswordInput.tsx
Labels: feature

#78 feat: 자유게시판 메인페이지 ui작업
  app/(routes)/boards/page.tsx
  app/(routes)/boards/type/Article.ts
  app/(routes)/layout.tsx
  app/_components/boards/ArticleCard.tsx
  app/_components/boards/BestArticleCard.tsx
  app/_components/boards/BestArticleList.tsx
  app/_components/boards/Card.tsx
  app/_components/boards/MenuDropdown.tsx
  app/_components/boards/Search.tsx
  app/_components/boards/SortDropdown.tsx
  app/_components/layout/Header/index.tsx
  package-lock.json
  package.json
  public/icons/ic-like.svg
  public/icons/ic-liked.svg
  public/icons/ic-medal.svg
  public/icons/ic-search-board.svg
Labels: feature

#81 리스트 페이지 1차 dev merge
  app/(routes)/task-list/_components/DateSelector.tsx
  app/(routes)/task-list/_components/TaskCard.tsx
  app/(routes)/task-list/_components/TaskListNav.tsx
  app/(routes)/task-list/page.tsx
  app/_components/common/ShadCN/Calendar/button.tsx
  app/_components/common/ShadCN/Calendar/calendar.tsx
  app/_components/common/ShadCN/Popover/popover.tsx
  app/_lib/utils/format-date.ts
  app/lib/utils.ts
  components.json
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feature

#82 TaskSection에 useGetTaskList hook 추가
  app/(routes)/task-list/_components/TaskCard.tsx
  app/(routes)/task-list/_components/TaskSection.tsx
  app/(routes)/task-list/page.tsx
  app/_hooks/useTask.ts
  app/_hooks/useTaskList.ts
Labels: feature

#87 feat: TaskDateSelector 컴포넌트에 인터렉션 기능 추가 및 컴포넌트 명 변경
  app/(routes)/team/[teamid]/task-lists/[listId]/_components/TaskCard.tsx
  app/(routes)/team/[teamid]/task-lists/[listId]/_components/TaskDateSelector.tsx
  app/(routes)/team/[teamid]/task-lists/[listId]/_components/TaskListNav.tsx
  app/(routes)/team/[teamid]/task-lists/[listId]/_components/TaskSection.tsx
  app/(routes)/team/[teamid]/task-lists/[listId]/page.tsx
Labels: feature

#79 Chore/69 스토리북 세팅
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  app/_styles/globals.css
  app/layout.tsx
  package-lock.json
  package.json
  stories/Button.stories.ts
  stories/modal.stories.ts
Labels: chore

#84 Feat/80 모달 input 컴포넌트로 변경
  app/_components/common/Input/EmailInput.tsx
  app/_components/common/Input/Input.tsx
  app/_components/common/Input/PasswordInput.tsx
  app/_components/modal/AddTaskListModal.tsx
  app/_components/modal/AddTaskModal.tsx
  app/_components/modal/ChangePasswordModal.tsx
  app/_components/modal/ResetPasswordModal.tsx
  app/_hooks/useArticle.ts
  app/_hooks/useArticleComment.ts
  app/_hooks/useTaskList.ts
Labels: feature, refactor

#90 Feat/86 add interaction to date selector component
  app/(routes)/team/[teamid]/task-lists/[listId]/_components/TaskListNav.tsx
  app/(routes)/team/[teamid]/task-lists/[listId]/_components/TaskSection.tsx
  app/(routes)/team/[teamid]/task-lists/[listId]/page.tsx
Labels: feature

#98 Feat/96 connect betweent listpage and modals
  app/(routes)/task-lists/[listId]/_components/TaskCard.tsx
  app/(routes)/task-lists/[listId]/_components/TaskDateSelector.tsx
  app/(routes)/task-lists/[listId]/_components/TaskListNav.tsx
  app/(routes)/task-lists/[listId]/_components/TaskSection.tsx
  app/(routes)/task-lists/[listId]/page.tsx
  app/(routes)/team/[teamid]/task-lists/[listId]/_components/TaskCard.tsx
  app/(routes)/team/[teamid]/task-lists/[listId]/_components/TaskDateSelector.tsx
  app/(routes)/team/[teamid]/task-lists/[listId]/page.tsx
  app/_components/modal/AddTaskListModal.tsx
  app/_components/modal/AddTaskModal.tsx
  app/_components/modal/DeleteTaskModal.tsx
Labels: feature

#99 Feat/97 로그인 & 회원가입 기능 구현
  app/(routes)/Login/page.tsx
  app/(routes)/signUp/page.tsx
  app/_components/common/Input/PasswordInput.tsx
  app/_components/login/LoginForm.tsx
  app/_components/login/SimpleLogin.tsx
  app/_components/signup/signupForm.tsx
  package-lock.json
Labels: feature

#100 랜딩페이지 구현
  app/page.tsx
  public/icons/done_fill.svg
  public/icons/folder_fill.svg
  public/icons/ic_repair.svg
  public/icons/message_fill.svg
  public/images/mockup01.png
  public/images/mockup02.png
  public/images/mockup03.png
  tailwind.config.ts
Labels: feature
